channels:
  - defaults
  - plotly
  - conda-forge
  - anaconda
dependencies:
  - ipykernel==5.3.4
  - ipython==7.22.0
  - ipykernel==5.3.4
  - ipywidgets==7.5.1
  - jupyter==1.0.0
  - jupyter_client==6.1.12
  - jupyter_console==6.2.0
  - jupyter_contrib_core==0.3.3
  - jupyter_contrib_nbextensions==0.5.1
  - jupyter_core==4.7.1
  - jupyterlab-plotly-extension>=1.0.0
  - jupyterlab==3.2.8
  - jupyterlab_pygments==0.1.2
  - matplotlib==3.4.2
  - numpy==1.20.2
  - pandas==1.1.3
  - pip==21.1.1
  - plotly==4.14.3
  - python==3.8.10
  - scikit-learn==0.23.2
  - scipy==1.6.2
  - wheel==0.36.2
  - pip:
    - cufflinks==0.17.3
